app.version=1.0.0
app.url=https://example.com/api
app.timeout=5000
app.name=MoodBot

spring.config.location=optional:file:./config*/
#
telegram.bot.name=Arturs_job4j_boost_mood_bot
telegram.bot.token=8665244699:AAGktQHR8iqMlb5dC8liQKivzw6uecrL7N8

# ????? ?????? SOCKS5 ?????? (Tor Browser)
telegram.proxy.host=127.0.0.1
# ???? ?????? SOCKS5 ?????? (Tor Browser)
telegram.proxy.port=9150